meta_product_name: "GÉP MONSTER"
meta_title: "Gep.Monster"
meta_description: "A gépi fordítások oldala! Közvetlen elérés a legnagyobb fordítás fájlokhoz is! Már több mint 1900 fordítás érhető el közvetlenül a szerverről."
meta_image: "1.png" # should exist in `app/assets/images/`